<?php

namespace Helldar\DigitText;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-08 at 18:20:32.
 */
class DigitTextTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DigitText
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DigitText;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Helldar\DigitText\DigitText::text
     * @todo   Implement testText().
     */
    public function testText()
    {
        $result0  = $this->object->text();
        $result1  = $this->object->text(64);
        $result2  = $this->object->text(764);
        $result3  = $this->object->text(2866);
        $result4  = $this->object->text(10383);
        $result5  = $this->object->text(14383);
        $result6  = $this->object->text(20383);
        $result7  = $this->object->text(72383);
        $result8  = $this->object->text(764383);
        $result9  = $this->object->text(700383);
        $result10 = $this->object->text(2644383);
        $result11 = $this->object->text(7644383);
        $result12 = $this->object->text(76443783);
        $result13 = $this->object->text(786443783);
        $result14 = $this->object->text(700443200);
        $result15 = $this->object->text(564.23);
//
        $this->assertEquals('ноль', $result0);
        $this->assertEquals('шестьдесят четыре', $result1);
        $this->assertEquals('семьсот шестьдесят четыре', $result2);
        $this->assertEquals('две тысячи восемьсот шестьдесят шесть', $result3);
        $this->assertEquals('десять тысяч триста восемьдесят три', $result4);
        $this->assertEquals('четырнадцать тысячи триста восемьдесят три', $result5);
        $this->assertEquals('двадцать тысяч триста восемьдесят три', $result6);
        $this->assertEquals('семьдесят две тысячи триста восемьдесят три', $result7);
        $this->assertEquals('семьсот шестьдесят четыре тысячи триста восемьдесят три', $result8);
        $this->assertEquals('семьсот тысяч триста восемьдесят три', $result9);
        $this->assertEquals('два миллиона шестьсот сорок четыре тысячи триста восемьдесят три', $result10);
        $this->assertEquals('семь миллионов шестьсот сорок четыре тысячи триста восемьдесят три', $result11);
        $this->assertEquals('семьдесят шесть миллионов четыреста сорок три тысячи семьсот восемьдесят три', $result12);
        $this->assertEquals('семьсот восемьдесят шесть миллионов четыреста сорок три тысячи семьсот восемьдесят три', $result13);
        $this->assertEquals('семьсот миллионов четыреста сорок три тысячи двести', $result14);
        $this->assertEquals('пятьсот шестьдесят четыре', $result15);
    }

    /**
     * @covers Helldar\DigitText\DigitText::digits
     * @todo   Implement testDigits().
     */
    public function testDigits()
    {

    }

    /**
     * @covers Helldar\DigitText\DigitText::dsort
     * @todo   Implement testDsort().
     */
    public function testDsort()
    {

    }

    /**
     * @covers Helldar\DigitText\DigitText::decline
     * @todo   Implement testDecline().
     */
    public function testDecline()
    {
        $result0 = $this->object->decline(1, 54);
        $result1 = $this->object->decline(2, 25);
        $result3 = $this->object->decline(3, 56);

        $this->assertEquals(' тысячи', $result0);
        $this->assertEquals(' миллионов', $result1);
        $this->assertEquals('', $result3);
    }
}
