<?php

namespace Helldar;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-07 at 21:14:56.
 */
class DigitTextTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DigitText
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Helldar\DigitText();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Helldar\DigitText::getText
     * 
     * @todo   Implement testGetText().
     */
    public function testGetText()
    {
        $digit1 = $this->object->getText(1);
        $digit2 = $this->object->getText(2);
        $digit3 = $this->object->getText(3);
        $digit4 = $this->object->getText();

        $this->assertEquals('один', $digit1);
        $this->assertEquals('два', $digit2);
        $this->assertEquals('три', $digit3);
        $this->assertEquals('ноль', $digit4);
    }

}
